; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1


Gui Calculator: New
Gui, Font, Segoe UI
Gui Add, Button, x163 y413 w75 h48, &OK
Gui Add, Button, x3 y413 w75 h48, &OK
Gui Add, Button, x243 y413 w75 h48, &OK
Gui Add, Button, x83 y413 w75 h48, &OK
Gui Add, Button, x83 y365 w75 h48, &OK
Gui Add, Button, x83 y317 w75 h48, &OK
Gui Add, Button, x3 y269 w75 h48, &OK
Gui Add, Button, x3 y221 w75 h48, &OK
Gui Add, Button, x3 y173 w75 h48, &OK
Gui Add, Button, x243 y173 w75 h48, &OK
Gui Add, Button, x163 y173 w75 h48, &OK
Gui Add, Button, x83 y173 w75 h48, &OK
Gui Add, Button, x83 y221 w75 h48, &OK
Gui Add, Button, x243 y221 w75 h48, &OK
Gui Add, Button, x163 y221 w75 h48, &OK
Gui Add, Button, x83 y269 w75 h48, &OK
Gui Add, Button, x163 y269 w75 h48, &OK
Gui Add, Button, x243 y269 w75 h48, &OK
Gui Add, Button, x3 y317 w75 h48, &OK
Gui Add, Button, x243 y317 w75 h48, &OK
Gui Add, Button, x163 y317 w75 h48, &OK
Gui Add, Button, x3 y365 w75 h48, &OK
Gui Add, Button, x243 y365 w75 h48, &OK
Gui Add, Button, x163 y365 w75 h48, &OK
Gui Add, Button, x19 y137 w48 h29, &OK
Gui Add, Button, x67 y137 w48 h29, &OK
Gui Add, Button, x115 y137 w48 h29, &OK
Gui Add, Button, x163 y137 w48 h29, &OK
Gui Add, Button, x211 y137 w48 h29, &OK
Gui Add, Button, x259 y137 w48 h29, &OK
Gui Add, Edit, x0 y56 w321 h75 +Number +Right, `n`n`n0
Gui Add, Button, x0 y5 w48 h48, &OK
Gui Font, s14 Norm
Gui Add, Text, x56 y5 w92 h42 +0x200, Standard
Gui Font
Gui Add, Button, x272 y5 w48 h48, &OK

Gui Show, w325 h467, Window
Return

CalculatorGuiEscape:
CalculatorGuiClose:
    ExitApp
