; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui +Resize
Gui Add, Picture, x9 y4 w40 h36, C:\_Umbra Sector\_Resources\1485347325_EditDocument.ico
Gui Font, s14, Verdana
Gui Add, Text, x68 y4 w120 h38 +0x200, Standard
Gui Font
Gui Add, Picture, x284 y12 w29 h20, C:\_Umbra Sector\_Resources\1485347325_EditDocument.ico
Gui Add, Edit, x9 y48 w302 h99, .
Gui Add, Button, x14 y155 w45 h26, &OK
Gui Add, Button, x62 y155 w45 h26, &OK
Gui Add, Button, x110 y155 w45 h26, &OK
Gui Add, Button, x158 y155 w45 h26, &OK
Gui Add, Button, x206 y155 w45 h26, &OK
Gui Add, Button, x255 y155 w45 h26, &OK
Gui Add, Button, x15 y187 w62 h47, &OK
Gui Add, Button, x88 y187 w63 h47, &OK
Gui Add, Button, x162 y187 w62 h47, &OK
Gui Add, Button, x237 y187 w62 h47, &OK
Gui Add, Button, x16 y240 w62 h45, &OK
Gui Add, Button, x88 y240 w62 h47, &OK
Gui Add, Button, x160 y240 w62 h47, &OK
Gui Add, Button, x240 y240 w62 h45, &OK
Gui Add, Button, x16 y288 w62 h47, &OK
Gui Add, Button, x16 y352 w62 h47, &OK
Gui Add, Button, x16 y408 w62 h47, &OK
Gui Add, Button, x16 y456 w62 h47, &OK

Gui Show, w321 h501, Calculator ‎- Calculator (Clone)
Return

GuiEscape:
GuiClose:
    ExitApp
